baseurl: ""

markdown: kramdown
relative_permalinks: false

include:
  - _pages
  - .htaccess

exclude:
  - node_modules/
  - package.json
  - Gruntfile.js
  - deploy_credentials.json
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: assets/css
  style: compressed

gems:
  - octopress-autoprefixer
