# Site settings
title: Bakir Immobilien
email: '&#105;&#110;&#102;&#111;&#064;&#098;&#097;&#107;&#105;&#114;&#105;&#109;&#109;&#111;&#098;&#105;&#108;&#105;&#101;&#110;&#046;&#100;&#101;'
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bakirimmobilien
github_username:  bakirimmobilien

# Build settings
markdown: kramdown
relative_permalinks: false

exclude:
  - node_modules/
  - package.json
  - Gruntfile.js
  - deploy_credentials.json

sass:
  sass_dir: assets/css
  style: compressed

logo-img: "/assets/img/bakirimmobilien_logo.svg"
