<?php

$typeMap = [
	'kaufen' => [
		'title' => 'Immobilienangebote zum Kauf',
		'types' => [
			'Einfamilienhaus',
			'Mehrfamilienhaus',
			'Zimmer',
			'Wohnung',
			'Dachgeschoss',
			'Maisonette',
			'Loft',
			'Penthouse',
			'Terrassen',
			'Etage',
			'Erdgeschoss',
			'Souterrain',
			'Apartment',
			'Ferienwohnung',
			'Galerie',
			'Rohdachboden',
			'Attikawohnung'
		],
		'marketing' => [
			'buy'
		]
	],
	'mieten' => [
		'title' => 'Immobilienangebote zur Miete',
		'types' => [
			'Zimmer',
			'Wohnung',
			'Dachgeschoss',
			'Maisonette',
			'Loft',
			'Penthouse',
			'Terrassen',
			'Etage',
			'Erdgeschoss',
			'Souterrain',
			'Apartment',
			'Ferienwohnung',
			'Galerie',
			'Rohdachboden',
			'Attikawohnung',
			'Reihenhaus',
			'Reihenend',
			'Reihenmittel',
			'Reiheneck',
			'Doppelhaushälfte',
			'Einfamilienhaus',
			'Stadthaus',
			'Bungalow',
			'Villa',
			'Resthof',
			'Bauernhaus',
			'Landhaus',
			'Schloss',
			'Zweifamilienhaus',
			'Mehrfamilienhaus',
			'Ferienhaus',
			'Berghütte',
			'Chalet',
			'Strandhaus',
			'Laube',
			'Apartmenthaus',
			'Burg',
			'Herrenhaus',
			'Finca',
			'Rustico',
			'Fertighaus',
			'Haus'
		],
		'marketing' => [
			'rent'
		]
	],
	'gewerbe-kaufen' => [
		'title' => 'Gewerbe zum Kauf',
		'types' => [
			'Bürofläche',
			'Bürohaus',
			'Bürozentrum',
			'Atelier',
			'Praxis',
			'Praxisfläche',
			'Praxishaus',
			'Büro Auststellungsfläche',
			'Coworking Space',
			'Shared Office',
			'Ladenlokal',
			'Einzelhandelsladen',
			'Verbrauchermarkt',
			'Einkaufszentrum',
			'Kaufhaus',
			'Factory Outlet',
			'Kiosk',
			'Verkaufsfläche',
			'Einzelhandel Ausstellungsfläche',
			'Gastronomie',
			'Gastronomie und Wohnung',
			'Pension',
			'Hotel',
			'Beherbergung',
			'Bar',
			'Cafe',
			'Diskothek',
			'Restaurant',
			'Raucherlokal',
			'Einraumlokal',
			'Halle',
			'Industriehalle',
			'Lager',
			'Lagerfläche',
			'Lager mit Freifläche',
			'Hochregallager',
			'Speditionslager',
			'Produktionshalle',
			'Werkstatt',
			'Servicehalle',
			'Freifläche',
			'Kühlhaus'
		],
		'marketing' => [
			'buy'
		]
	],
	'gewerbe-mieten' => [
		'title' => 'Gewerbe zur Miete',
		'types' => [
			'Bürofläche',
			'Bürohaus',
			'Bürozentrum',
			'Atelier',
			'Praxis',
			'Praxisfläche',
			'Praxishaus',
			'Büro Auststellungsfläche',
			'Coworking Space',
			'Shared Office',
			'Ladenlokal',
			'Einzelhandelsladen',
			'Verbrauchermarkt',
			'Einkaufszentrum',
			'Kaufhaus',
			'Factory Outlet',
			'Kiosk',
			'Verkaufsfläche',
			'Einzelhandel Ausstellungsfläche',
			'Gastronomie',
			'Gastronomie und Wohnung',
			'Pension',
			'Hotel',
			'Beherbergung',
			'Bar',
			'Cafe',
			'Diskothek',
			'Restaurant',
			'Raucherlokal',
			'Einraumlokal',
			'Halle',
			'Industriehalle',
			'Lager',
			'Lagerfläche',
			'Lager mit Freifläche',
			'Hochregallager',
			'Speditionslager',
			'Produktionshalle',
			'Werkstatt',
			'Servicehalle',
			'Freifläche',
			'Kühlhaus'
		],
		'marketing' => [
			'rent'
		]
	],
	'grundstuecke' => [
		'title' => 'Grundstücke',
		'types' => [
			'Wohngrundstück',
			'Gewerbegrundstück',
			'Industriegrundstück',
			'Landwirtschaftsgrundstück',
			'Freizeitgrundstück',
			'Grundstück',
			'Grundstück für Gewerbepark',
			'Grundstück mit Sondernutzung',
			'Seeliegenschaft'
		]
	]
];
